### ISSUE TITLE
There is a Persistent Cross-Site Scripting in the member contributions.

### ISSUE THREAD

**Issue by wantwo3** [weng-xianhu/eyoucms#12]
Vulnerability found in Eyoucms1.4.6 and before.
In the member center member contribution office, after editing the contribution content through the editor, intercept the data package, modify the parameter addonfieldext [content], and construct the payload "< img SRC = 1 onerror = alert（ document.cookie )>”
![image](https://user-images.githubusercontent.com/13793949/83213556-fbcd7800-a194-11ea-9ea1-fe8b4a4553bf.png)
![image](https://user-images.githubusercontent.com/13793949/83213577-0e47b180-a195-11ea-9b73-a710b58001af.png)
After the administrator logs in the background, when viewing the content submitted by the user, it triggers the payload to obtain the cookie information.
![image](https://user-images.githubusercontent.com/13793949/83213594-1bfd3700-a195-11ea-8991-e7fa33ff621f.png)

**Comment by weng-xianhu** [comment]
已修复
