### ISSUE TITLE
There is SQL injection in your source code

### ISSUE THREAD

**Issue by lcg-22266** [weng-xianhu/eyoucms#13]
The vulnerability affects http://127.0.0.1/eyoucms/index.php , tid
URL encoded POST input tid was set to 1À§À¢%2527%2522

Use BurpSuite

![SQL injection](https://user-images.githubusercontent.com/68074499/87068260-e6457680-c247-11ea-99d2-6c94067e69d4.png)

**Comment by weng-xianhu** [comment]
已修复
