### ISSUE TITLE
Bind email address in user's function lead to XSS

### ISSUE THREAD

**Issue by H4niz** [weng-xianhu/eyoucms#18]
I and @KietNA-HPT found a XSS vulnerability on a user function called `bind_email()` when we audit your source code. The vulnerability occurs when we input new email with injecting some trick to trigger XSS in `title` param like: 
```
index.php?m=user&c=Users&a=bind_email&title=123%27;+window.open("www.google.com.vn");//
```
 To trigger this bug, we did following below:
1. Access url: http://example-host.com/index.php?m=user&c=Users&a=bind_email&title=triggerxss%27;+window.open("www.google.com.vn");//
2. Enter a valid email
3. Click to `Send` (`点击发送` in your language) button. And then the XSS is triggered.

**Solution:** To fix this vulnerability, please validate input from user into `title` param

**Comment by weng-xianhu** [comment]
已修复
