### ISSUE TITLE
There is a blind xxe vulnerability

### ISSUE THREAD

**Issue by lavon321** [weng-xianhu/eyoucms#19]
wechat_return function in application\home\controller\Index.php passes user's input directly into simplexml_ load_ String function, and external entities are not prohibited here, causing the xxe vulnerability
![image](https://user-images.githubusercontent.com/50451123/136346681-11357f18-62b5-49af-9515-24231ae207b4.png)
Here, you need to query the pay_info whose pay_mark field is wechat from the pay_api_config table of the database. After deserializing the pay_info, judge whether the appid is empty or whether the input XML contains '[appid]'
![image](https://user-images.githubusercontent.com/50451123/136347860-ec674e63-c4d1-4a40-a7ec-4fad49ee88a6.png)
The operation of inserting the pay_api_config table was found in the wechatpayconfig function of the application\admin\controller\PayApi.php file
![image](https://user-images.githubusercontent.com/50451123/136348215-5d0079e8-1d75-4dde-8a9b-064b7cc17750.png)

Administrator permission is required to configure wechat payment interface
Log in to the background and configure wechat payment in basic information - > interface configuration
![image](https://user-images.githubusercontent.com/50451123/136348935-78f6c7a6-f35d-46e4-874e-f19220b7426a.png)
Remember the 'pay_info[appid]'
![image](https://user-images.githubusercontent.com/50451123/136349110-7ca3ab05-8c04-4e48-b3d8-46131a28b6ba.png)
Then you can verify the blind xxe in the foreground. The payload needs to contain '[appid]', here is '[3]'
![image](https://user-images.githubusercontent.com/50451123/136349225-1de08c7c-40ef-4d33-a1a0-3018b643586b.png)
dnslog received request
![image](https://user-images.githubusercontent.com/50451123/136349302-faf0ea91-4248-45d4-b008-6d80de949915.png)

**Comment by weng-xianhu** [comment]
已修复
