### ISSUE TITLE
EyouCMS v1.5.7 has a vulnerability, stored cross-site scripting (XSS)

### ISSUE THREAD

**Issue by MarkTop1** [weng-xianhu/eyoucms#23]
**Background upload image, by modifying the image name to generate cross-site request forgery**

1, first open content management, click Publish document, click Upload file
![图片1](https://user-images.githubusercontent.com/73089544/156514015-b997003f-6433-4bfd-a645-ab4beb9949d7.png)
![图片2](https://user-images.githubusercontent.com/73089544/156514043-afa7215a-4bf1-40f2-b813-fde072674c83.png)
2. Set up proxy packet capture before clicking upload image, upload a valid JPG image, find the name of the image and change it to: 

![(R_66ZTRKX(%UIF88@Z 5BD](https://user-images.githubusercontent.com/73089544/156514521-a0a7bf0c-9353-4b5f-aa6e-f24d0ac37caa.png)

![图片3](https://user-images.githubusercontent.com/73089544/156514288-49d7f3db-7d0f-4fb2-a4a5-f3ff8d6f267c.png)
![图片4](https://user-images.githubusercontent.com/73089544/156514302-77085d64-5ada-4c3d-b3db-d2cc0bbb02d4.png)

![图片5](https://user-images.githubusercontent.com/73089544/156514582-db5cdae2-c580-42a0-aef3-eba3b79b89c5.png)

![图片6](https://user-images.githubusercontent.com/73089544/156514312-03286d8a-c42f-41de-928c-841302172262.png)
b949ada.png)

Other impacts: The file name of the vulnerability is saved in the database. When the system is built using phpstudy, a word written into the Trojan horse will appear in "ey_uploads.MYD"  in the mysql directory. If any file contains the vulnerability, the vulnerability will be directly getshell

![图片7](https://user-images.githubusercontent.com/73089544/156516256-6ff8c28d-a72a-4a6c-9fac-dfc091671eeb.png)

![图片8](https://user-images.githubusercontent.com/73089544/156516264-067e4bd6-12cf-455e-90dd-672d3ab2efac.png)

**Comment by weng-xianhu** [comment]
已修复
