### ISSUE TITLE
EyouCMS v1.5.8 has a vulnerability, stored cross-site scripting (XSS)

### ISSUE THREAD

**Issue by xxhzz99** [weng-xianhu/eyoucms#25]
version：V1.5.8-UTF8-SP1
![image](https://user-images.githubusercontent.com/54786000/177534611-4ef57673-cd01-421e-ae37-253d856ce2bd.png)

1、So you log in to the front desk member, click "I want to contribute", insert payload in the title of the article.
payload:<style onload=alert(document.cookie) />
![image](https://user-images.githubusercontent.com/54786000/177534773-19dc0878-a9c1-4719-9e53-6ecfaf9796ef.png)

2、Check the parameter and find title
![image](https://user-images.githubusercontent.com/54786000/177535214-1085d9f7-33f0-4d59-94f9-95fead593f04.png)
3、Successful submission
![image](https://user-images.githubusercontent.com/54786000/177535404-4a1d5711-a54f-4cb6-902d-4922a0df4caf.png)
4、Log in to the background and view the content submitted by users
![image](https://user-images.githubusercontent.com/54786000/177535592-fe108941-b923-4ebf-998c-7921ed080bdf.png)

5、Check the submitted content, successfully trigger XSS attack code, pop-up cookie sensitive information
![image](https://user-images.githubusercontent.com/54786000/177535920-8c8f748c-1c65-4cc1-9329-974a57fc7e99.png)

**Comment by weng-xianhu** [comment]
已修复，v1.6.2版本发布
