### ISSUE TITLE
Vulnerability: EyouCMS v1.6.0 has a vulnerability that stores cross-site scripting (XSS)

### ISSUE THREAD

**Issue by h18192h** [weng-xianhu/eyoucms#39]
Version：V1.6.0-UTF8-SP1
![屏幕截图1](https://user-images.githubusercontent.com/83074322/202837935-26b30126-1f5f-4047-82f2-f92859b1b81e.jpg)
1. Go to the background --> basic information--> home page description
![图片2](https://user-images.githubusercontent.com/83074322/202837990-8acd9355-f6bd-4392-80ca-377a52eab003.png)
Construct the JS script at the home page description and submit it.Payload:"><script>alert("XSS");</script>
2. Open the EyouCMS client
![图片3](https://user-images.githubusercontent.com/83074322/202838068-f1de8014-7464-4744-8579-e38676e1fcea.png)

**Comment by weng-xianhu** [comment]
感谢反馈
