### ISSUE TITLE
There is a stored xss in basic_information(基本信息)

### ISSUE THREAD

**Issue by Lilc1** [weng-xianhu/eyoucms#6]
Tested in 1.3.6 version
![image](https://user-images.githubusercontent.com/55877767/66696704-ca389700-ed00-11e9-9326-7598d8962b84.png)
![image](https://user-images.githubusercontent.com/55877767/66696725-f522eb00-ed00-11e9-9470-465103748709.png)

**Comment by weng-xianhu** [comment]
Recovered
